/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.POO;

import javax.swing.JOptionPane;

/**
 *
 * @author aitor
 */
public class Frm_POO extends javax.swing.JFrame {

    /**
     * Creates new form Frm_POO
     */
    public Frm_POO() {
        initComponents();
    }
    public void MostrarPadre(Padre p1){
        txtA.setText(null);
        txtA.append("El nombre es: "+p1.getNombre()+"\n");
        txtA.append("La edad es: "+p1.getEdad()+"\n");
        txtA.append("El sueldo es: "+p1.getSueldo()+"\n");
    }
    public void MostrarHija(Hija h1){
        txtA.setText(null);
        txtA.append("El nombre es: "+h1.getNombre()+"\n");
        txtA.append("La edad es: "+h1.getEdad()+"\n");
        txtA.append("El sueldo es: "+h1.getSueldo()+"\n");
        txtA.append("La carrera es: "+h1.getCarrera()+"\n");
    }
    
     public void MostrarNieta(Nieta n1){
        txtA.setText(null);
        txtA.append("El nombre es: "+n1.getNombre()+"\n");
        txtA.append("La edad es: "+n1.getEdad()+"\n");
        txtA.append("El sueldo es: "+n1.getSueldo()+"\n");
        txtA.append("La carrera es: "+n1.getCarrera()+"\n");
        txtA.append("La música es: "+n1.getMusica()+"\n");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnPadre = new javax.swing.JButton();
        btnHija = new javax.swing.JButton();
        btnNieta = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtA = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel1.setText("POO");

        btnPadre.setText("PADRE");
        btnPadre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPadreActionPerformed(evt);
            }
        });

        btnHija.setText("HIJA");
        btnHija.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHijaActionPerformed(evt);
            }
        });

        btnNieta.setText("NIETA");

        txtA.setColumns(20);
        txtA.setRows(5);
        jScrollPane1.setViewportView(txtA);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(366, 366, 366)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(205, 205, 205)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnPadre, javax.swing.GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE)
                            .addComponent(btnHija, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnNieta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 679, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(136, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(btnPadre, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(btnHija, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNieta, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPadreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPadreActionPerformed
        String nom= JOptionPane.showInputDialog(this,"Ingresa el nombre: ");
        Padre p1= new Padre(nom,90,8000);
        MostrarPadre(p1);
        
                
                ///public Padre(String nombre, int edad, double sueldo) {
                    //this.nombre = nombre;
                    //this.edad = edad;
                    //this.sueldo = sueldo;

    }//GEN-LAST:event_btnPadreActionPerformed

    private void btnHijaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHijaActionPerformed
        Hija h1= new Hija("Sistemas","Merlina",90,8000);
        MostrarPadre(h1);
        
        //public Hija(String carrera, String nombre, int edad, double sueldo) {
        //super(nombre, edad, sueldo);
        //this.carrera = carrera;
    
    }//GEN-LAST:event_btnHijaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_POO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_POO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_POO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_POO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm_POO().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHija;
    private javax.swing.JButton btnNieta;
    private javax.swing.JButton btnPadre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtA;
    // End of variables declaration//GEN-END:variables
}
